vayu_defconfig: remove DEBUG_FS and everything belonging to it.
This fixes the following:
checkvintf E 12-13 20:53:00  8470  8470 check_vintf.cpp:554] files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
checkvintf E 12-13 20:53:00  8470  8470 check_vintf.cpp:554] For kernel requirements at matrix level 5, For config CONFIG_DEBUG_FS, value = y but required n
RuntimeError: VINTF compatibility check failed

Signed-off-by: ouroboros420 <42john42smith@googlemail.com>